### ISSUE TITLE
disco#info on a room reports its decription for its name

### ISSUE THREAD

**Issue by RobertLarsen** [twonds/palaver#7]
Wouldn't the room name be more relevant?

That is:

```
        result_list.append(disco.Identity('conference', 'text',
                                          room['roomname']))
```

instead of:

```
        result_list.append(disco.Identity('conference', 'text',
                                          room['description']))
```

**Comment by twonds** [comment]
I believe in storage the room['name'] is actually the jid name, so it is more appropriate to display the description. You get the jid name and room description, instead of repeating the jid name.

**Comment by RobertLarsen** [comment]
Both room['name'] and room['description'] are initialized to the node part of the jid, but you can change them with muc#owner. That doesn't change the jid.
These two configuration fields are assigned to the room['name'] and room['description'] respectively:

```
<field var="muc#roomconfig_roomname"
       type="text-single"
       label="Natural language room name.">
<value>
abc
</value>
</field>
<field var="muc#roomconfig_roomdesc"
       type="text-multi"
       label="Short description of room.">
<value>
abc
</value>
</field>
```

**Comment by twonds** [comment]
I seemed to have been mistaken. Commited the above change.

**Comment by RobertLarsen** [comment]
Marvellous :+1
